# -*- coding: utf-8 -*-
"""sentence trans

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18713cfpuS2dV0JdYeTCD6aiLVv_SRVJn
"""

!pip install sentence-transformers

from sentence_transformers import SentenceTransformer,util

#load the model
model = SentenceTransformer('all-MiniLM-L6-V2')

#take input from user
text1 =input("enter Text 1: ")
text2 =input("enter Text 2: ")

#convert text to embeddings
embedding1 = model.encode(text1)
embedding2 = model.encode(text2)

#calculate similarity
similarity = util.cos_sim(embedding1,embedding2)

#show result
print("\n similarity score:",round(float(similarity),2))

if similarity > 0.75:
   print("similarity Level : High")
elif similarity > 0.4:
  print("similarity Level : Medium")
else:
  print("similarity Level : Low")