# -*- coding: utf-8 -*-
"""tourch

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lr9U7NhLbXGKfduSem5GbsZfNYObpzNg
"""

!pip install Transformers torch

from transformers import pipeline

#load text generation model(GenAI)
generator = pipeline(
    "text-generation",
    model = "gpt2"
)

#input prompt
prompt = "Artificial Intelligence in finance will be"

#generate text
result = generator(prompt , max_length=50, num_return_sequences=1)

print("AI generated text :")
print(result[0]['generated_text'])